---
title: "Data Visualization: COVID-19 Detour"
author: "Prof. Harbert"
date: "Part ???"
output: 
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: 4
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Disclaimer

The author of this page is not an epidemiologist. All data visualizations presented here are for code demonstration purposes only and are not meant to be a substitute for public health information. For current information we recommend: [the JHU Coronavirus dashboard](https://coronavirus.jhu.edu/map.html) and [Nextstrain](https://nextstrain.org/ncov)

# Data visualization: Coronavirus Data Trends

Goals 

+ Practice using dplyr and 
+ Experiment with interactive graphics with plotly
+ Work on higher level graphics operations like multipanel plots and saving high quality image files.
+ Visualize current trends in US COVID-19 cases

That's it. 

# The Raw Data {.tabset .tabset-fade .tabset-pills}

## Download GitHub Repo

The raw data compiled by Johns Hopkins University Center for Systems Science and Engineering and used in online [dashboards](https://coronavirus.jhu.edu/map.html) tracking the virus spread are publicly available in a [GitHub repository](https://github.com/CSSEGISandData/COVID-19).

We will clone the entire repository and access the data files within. 

```{bash, message=F, echo=F}
rm -R COVID-19
```

```{R}
system('git clone https://github.com/CSSEGISandData/COVID-19')
list.files('COVID-19')
```

## Explore

Inside this folder we have the current data from various government and international organizations tracking the spread of the Coronavirus. We will mostly use the 'csse_covid_19_data' which compiles the infection and death rates.

```{R}
list.files('COVID-19/csse_covid_19_data/csse_covid_19_time_series')
```

# Visualize {.tabset .tabset-fade .tabset-pills}

## Read 

Read case trends file:

```{R}
cases = read.csv('COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv')
colnames(cases)

```

Read death trends file: (work with this later)

```{R}
deaths = read.csv('COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv')
```


## Filter with dplyr

These tables are organized with one column for each date that they have tracked data. The R packages dplyr and ggplot2 do not work with this formatting exacly. Instead we need to rearrange so that each row contains only one value for cases/deaths and information in other columns about the geography and date that value applies to.

We also need to fix dates to an R compatible date format. With reshape2 and dplyr we can reorganize the data and convert date strings all at the same time:

```{R}
library(reshape2)
library(dplyr)
library(tibble)
library(stringr)

cases_df = melt(cases, 
               id.vars=c('Province.State', 'Country.Region', 'Lat', 'Long'), 
               measure.vars = grep('X', colnames(cases), value=T)
               ) %>% 
  mutate(variable=str_replace(variable, "X", "")) %>%
  mutate(variable=as.Date(variable, "%m.%d.%y"))

deaths_df = melt(deaths, 
               id.vars=c('Province.State', 'Country.Region', 'Lat', 'Long'), 
               measure.vars = grep('X', colnames(cases), value=T)
               ) %>% 
  mutate(variable=str_replace(variable, "X", "")) %>%
  mutate(variable=as.Date(variable, "%m.%d.%y"))

```

How would you use dplyr to filter for cases (or deaths) by geography (country and state)?

```{R}
#calculate running case total for each country by summing across state.province groups 
cases_notnull = cases_df %>% 
  group_by(Country.Region, variable) %>%
  summarize(total_cases=sum(value)) 

#oof, fix state abbreviations to names for US states:
us_cases = cases_df %>% 
  filter(Country.Region == 'US') %>%
  mutate(Province.State = str_extract(Province.State, '\\b[^,]+$')) %>%
  mutate(Province.State = ifelse(Province.State %in% state.abb,
                                 state.name[match(Province.State, state.abb)],
                                 Province.State)
  ) %>%
  group_by(Province.State, variable) %>%
  summarize(total_cases=sum(value))
  
#Get data for US cases in Massachusetts
ma_cases = us_cases %>% 
  filter(Province.State == 'Massachusetts')

```

## Global Trends

Plot Global case trend

```{R}
library(ggplot2)
# turn off scientific notation, show real numbers:
options(scipen=999, digits=1) 


ggplot(data=cases_notnull) +
  geom_path(aes(x=variable, 
                y=total_cases, 
                group=Country.Region, 
                col=Country.Region)
            ) +
  theme_minimal() +
  theme(legend.position = 'none') +
  xlab('Date') +
  ylab('Total Cases')

  
```

China (the top line) dominates that graph so what if we make the same graph but without China:

```{R}
cases_notchina = cases_notnull %>%
  filter(Country.Region != "China")

country_plot = ggplot(cases_notchina) +
  geom_path(aes(x=variable, 
                y=total_cases, 
                group=Country.Region, 
                col=Country.Region)
            ) +
  theme_minimal() +
  theme(legend.position = 'none') +  
  xlab('Date') +
  ylab('Total Cases')

```

That's better for showing the trends in other countries, but we have turned off the legend because it shows all countries that have cases (~125). Use geom_text() to add labels to the right of the end of each line.

```{R}
label_cou = ggplot(cases_notchina) +
  geom_path(aes(x=variable, 
                y=total_cases, 
                group=Country.Region, 
                col=Country.Region)
            ) +
  geom_text(data = cases_notchina %>% filter(variable == max(variable, na.rm=T)-1), 
            aes(label = Country.Region, colour = Country.Region, x = max(variable, na.rm=T), y = total_cases), hjust = "inward") +
  scale_color_discrete() + 
  theme_minimal() +
  theme(legend.position = 'none') +  
  xlab('Date') +
  ylab('Total Cases')

```



## US Trends

Let's apply the same thinking to plot the trend for all US States reporting cases:

Then plot:

```{R}
state_plot =ggplot(us_cases) +
  geom_path(aes(x=variable, 
                y=total_cases, 
                group=Province.State,
                col=Province.State)
            ) +
  geom_text(data = us_cases %>% filter(variable == max(variable, na.rm=T)-1), 
            aes(label = Province.State, colour = Province.State, x = max(variable, na.rm=T), y = total_cases), hjust = "inward") +
  theme_minimal() +
  theme(legend.position = 'none') +  
  xlab('Date') +
  ylab('Total Cases')

state_plot

```

## MA Trends

What about the cases in Massachusetts only?

```{R}
ma_plot = ggplot(ma_cases) +
  geom_path(aes(x=variable, 
                y=total_cases)
            ) +
  theme_minimal() +
  theme(legend.position = 'none') +
  xlab('Date') +
  ylab('Total Cases')

ma_plot

```

# Multipanel Plots

cowplot!

```{R}
library(cowplot)
cowplot = plot_grid(label_cou, state_plot, ma_plot, ncol=3, align = 'v', labels="AUTO")
cowplot

```


# Saving Plots

Use ggsave() to create image files of your ggplot images.

```{R}
dir.create('figures')
ggsave(cowplot, file='figures/corona_fig.png', height=6, width=12, units='in', dpi=600)
```

Which should look like [this]('./figures/corona_fig.png')


# Cumulative Infections Script

The graphs above show trends in active infection cases over time. Below is a self contained experimental R script to generate cumulative infection tables and graphs.

```{R}
#!/usr/bin/R
library(dplyr)
library(tibble)
library(ggplot2)
library(reshape2)
library(stringr)

#get data
system('git clone https://github.com/CSSEGISandData/COVID-19')

#load cases, deaths, recovered data
cases = read.csv('COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv')

cases_df = melt(cases, 
               id.vars=c('Province.State', 'Country.Region', 'Lat', 'Long'), 
               measure.vars = grep('X', colnames(cases), value=T)
               ) %>% 
  mutate(variable=str_replace(variable, "X", "")) %>%
  mutate(variable=as.Date(variable, "%m.%d.%y"))

cases_notnull = cases_df %>% 
  group_by(Country.Region, variable) %>%
  summarize(total_cases=sum(value)) 

ggplot(data=cases_notnull) +
  geom_path(aes(x=variable, 
                y=total_cases, 
                group=Country.Region, 
                col=Country.Region)
            ) +
  theme_minimal() +
  theme(legend.position = 'none') +
  xlab('Date') +
  ylab('Total Cases')


```