---
title: "COVID-19 Data Vis"
author: "Rob Harbert"
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output: 
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: 4
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Trends in COVID-19 Infection Cases {.tabset .tabset-fade .tabset-pills}

Here are a few simple interactive graphics tracking the Novel Coronavirus cases globally and in the US States. The aim of this page is to provide a simple interface to view trends in Coronavirus infection rates and compare between countries and within the US.

## Global Cases by Country

```{R, message=F, echo = F, warning=F}
library(dplyr)
library(tibble)
library(ggplot2)
library(reshape2)
library(stringr)
library(cowplot)
library(plotly)

#get data
system('rm -R COVID-19')
system('git clone https://github.com/CSSEGISandData/COVID-19')

#load cases, deaths, recovered data
cases = read.csv('COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv')

cases_df = melt(cases, 
               id.vars=c('Province.State', 'Country.Region', 'Lat', 'Long'), 
               measure.vars = grep('X', colnames(cases), value=T)
               ) %>% 
  mutate(variable=str_replace(variable, "X", "")) %>%
  mutate(variable=as.Date(variable, "%m.%d.%y")) %>%
  filter(Country.Region != "Diamond Princess") %>%
  filter(Country.Region != "Cruise Ship")

cases_notnull = cases_df %>% 
  group_by(Country.Region, variable) %>%
  summarize(total_cases=sum(value)) 

days_since500 = cases_notnull %>%
  group_by(Country.Region) %>%
  filter(total_cases >= 500) %>%
  mutate(days_since = 1:n())

cases_notchina = cases_notnull %>%
  filter(Country.Region != "China")

#create ggplot object
#plot global trends
label_cou = ggplot(cases_notnull %>% ungroup()) +
  geom_path(aes(x=variable, 
                y=total_cases, 
                group=Country.Region, 
                col=Country.Region)
            ) +
  geom_text(data = cases_notnull %>% filter(variable == max(variable, na.rm=T)-1), 
            aes(label = Country.Region, colour = Country.Region, x = max(variable, na.rm=T), y = total_cases), hjust = "inward") +
  scale_color_discrete() + 
  theme_minimal() +
  theme(legend.position = 'none') +  
  xlab('Date') +
  ylab('Total Cases')

#since 500 cases/country
cou500 = ggplot(days_since500 %>% ungroup()) +
  geom_path(aes(x=days_since, 
                y=total_cases, 
                group=Country.Region, 
                col=Country.Region)
            ) +
  scale_color_discrete() + 
  scale_y_log10() +
  theme_minimal() +
  theme(legend.position = 'none') +  
  xlab('Days Since 500 cases') +
  ylab('Total Cases')

#convert interactive plotly
pltly_lab = ggplotly(label_cou)
pltly_cou = ggplotly(cou500)

pltly_cou
```

Figure 1. Coronavirus Cases by Country. Confirmed case counts in each country from the [Johns Hopkins University Center for Systems Science and Engineering](https://coronavirus.jhu.edu/map.html) plotted on a log-scale. Linear increases in a log-scale graph indicate periods of exponential growth in the number of cases (exponential = doubling of cases per unit time). All curves shown from date of first 500 cases identified in each country to account for different dispersal times. View country identity and graph values by hovering over the lines. Use tool menue to zoom and rescale axes.

Interpretation: Most countries are increasing along a path that shows exponential growth in case counts is occurring. These trends are evidence of rapid spread that is ongoing in most countries. Note that Japan and South Korea begin to diverge from most of the other countries on this graphic.

## Trends by US States

```{R, message=F, echo=F, warning=F}

us_cases = cases_df %>% 
  filter(Country.Region == 'US') %>%
  mutate(Province.State = str_extract(Province.State, '\\b[^,]+$')) %>%
  mutate(Province.State = ifelse(Province.State %in% state.abb,
                                 state.name[match(Province.State, state.abb)],
                                 Province.State)
  ) %>%
  group_by(Province.State, variable) %>%
  summarize(total_cases=sum(value)) %>%
  filter(total_cases >= 10) %>%
  mutate(days_since = 1:n()) %>%
  filter(Province.State != "Diamond Princess") %>%
  filter(Province.State != "Grand Princess")

#create ggplot object
g2 = state_plot =ggplot(us_cases %>% ungroup()) +
  geom_path(aes(x=variable, 
                y=total_cases, 
                group=Province.State,
                col=Province.State)
            ) +
#  geom_text(data = us_cases %>% filter(variable == max(variable, na.rm=T)-1), 
           # aes(label = Province.State, colour = Province.State, x = max(variable, na.rm=T), y = total_cases), hjust = "inward") +
  scale_y_log10() +
  theme_minimal() +
  theme(legend.position = 'none') +  
  xlab('Date') +
  ylab('Total Cases')

#since 500 cases/country
state10 = ggplot(us_cases %>% ungroup()) +
  geom_path(aes(x=days_since, 
                y=total_cases, 
                group=Province.State, 
                col=Province.State)
            ) +
  scale_color_discrete() +
  scale_y_log10() +
  theme_minimal() +
  theme(legend.position = 'none') +  
  xlab('Days Since 10 cases') +
  ylab('Total Cases')



#convert interactive plotly
pltly_states1 = ggplotly(g2)
#pltly_states2 = ggplotly(state10)

pltly_states1

#subplot(pltly_states1, pltly_states2, nrows=2)

```
Figure 2. Coronavirus Cases by US State. Confirmed case counts in each US State with at least 10 cases from the [Johns Hopkins University Center for Systems Science and Engineering](https://coronavirus.jhu.edu/map.html) plotted on a log scale. Plotted by actual calendar date.

Interpretation: All states with active cases are exhibiting exponential growth. While case numbers may be small now these data suggest that rapid increases in identified Coronavirus cases are forthcoming. Note that California identified cases relatively early. However, Washington and New York have more cases presently. One possibility is that New York and Washington had Coronavirus cases earlier that were not identified and the rates of spread is similar to what has been observed in California. Despite Massachusetts being relatively small it ranks as the state with the 4th highest number of cases presently.

[home](devbioinformatics.org)

